# Generated by Django 4.1.5 on 2023-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('analyst', 'Analyst'), ('department_dir', 'Department Dir'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
