# Generated by Django 4.1.5 on 2023-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='code',
            field=models.CharField(choices=[('1', 'Russia'), ('2', 'Double'), ('3', 'Inostr'), ('4', 'Without')], default='4', max_length=1),
        ),
    ]
