# Generated by Django 4.1.5 on 2023-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_citizenship_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='status',
            field=models.CharField(choices=[('registered', 'Ok'), ('unregistered', 'Ntok')], default='unregistered', max_length=15),
        ),
    ]
