# Generated by Django 4.1.5 on 2023-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_migrant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_statement',
            name='status',
            field=models.CharField(choices=[('pending', 'First'), ('approval', 'Second'), ('approved', 'Third'), ('declined', 'Declined')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='unregistration_statement',
            name='status',
            field=models.CharField(choices=[('pending', 'First'), ('approval', 'Second'), ('approved', 'Third'), ('declined', 'Declined')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
    ]
